language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_API_LEVEL=25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.2
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    # Additional components
    - extra-android-m2repository
    # Emulator
    - sys-img-armeabi-v7a-google_apis-25
cache:
  directories:
    - $HOME/.gradle/caches/2.9
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
before_script:
    # Launch emulator before the execution
    - echo no | android create avd --force -n test -t android-25 --abi google_apis/armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
script:
  # Unit tests
  - ./gradlew rapid-sdk-android:testReleaseUnitTest

  # Instrumented tests
  - travis_wait ./gradlew rapid-sdk-android:connectedAndroidTest

  # If successful and Git TAG exists - publish to Bintray
  - '[[ -z $TRAVIS_TAG ]]  || ./gradlew rapid-sdk-android:bintrayUpload -q'